### ISSUE TITLE
Unable to Access Lantern

### ISSUE THREAD

**Issue by Joeathon** [martinohanlon/mcpi#10]
ISSUE: Unable to access elements such as lanterns with the MCPI.  https://minecraft.gamepedia.com/Lantern
SUGGESTION: 1) Update the MCPI package to include this capability.
SUGGESTION: 2) Update the Minecraft Wiki, to provide a python implementation example.
SUGGESTION: 3) Provide links to community forums in the readme, as to help the community better collaborate.
COMMENTS: This library is truly fantastic, and happy to contribute where I can.  For now it is just sharing observations.  However, I'm happy to participate in items such as updating the Wiki, if the community feels that would be beneficial.

**Comment by leha-code** [comment]
Lanterns don't exist in Minecraft Pi. If you're using the newer Minecraft versions, check your version, and the block ID.
