### ISSUE TITLE
getBlocks does not return data, only ids

### ISSUE THREAD

**Issue by jean-philippe-martin** [martinohanlon/mcpi#14]
My [understanding](https://www.stuffaboutcode.com/p/minecraft-api-reference.html) is that `getBlocks` should return the id and data for the blocks, but when I try it I only get ids, no data. Here is an example:

```
# Place a torch in front of me
>>> mc.setBlock(x,y,z, mcpi.block.Block(50,5))
# retrieve the information for that same block
>>> blocks = mc.getBlocks(x,y,z,x,y,z)
# Expected: [(50,5)]
>>> blocks
[50]
```

I'm using mcpi 1.2.0 on Python 2.7.

**Comment by martinohanlon** [comment]
.getBlocks only returns the block I'd

```
.getBlocks(x0,y0,z0,x1,y1,z1)
"Get a cuboid of blocks (x0,y0,z0,x1,y1,z1) => [id:int]"
```

**Comment by jean-philippe-martin** [comment]
I see, my understanding was wrong, thank you.
