### ISSUE TITLE
Two coding-persons on one server

### ISSUE THREAD

**Issue by OrleonForDev** [martinohanlon/mcpi#15]
Hello! When there are more than 1 person at server I have a problem with making code. The code runs for those person, who entered first on a server. (such commands as setTilePos and getTilePos) Even if the second pupil runs it. Is there any way to solve this problem? Or everybody needs to play only on his own local server?

**Comment by martinohanlon** [comment]
You can use the entity functions to get the position of all the players. player.x will always return the host player.
