### ISSUE TITLE
Feature request: GetBlocksWithData

### ISSUE THREAD

**Issue by jean-philippe-martin** [martinohanlon/mcpi#16]
Calling `getBlockWithData` in a loop is very slow. In contrast, getting even large areas with `getBlocks` is fast - but these don't include the data.

It would be very nice to have `getBlocksWithData` that returns the id and data for all blocks in between two coordinates (similar signature to `getBlockWithData`, richer outputs).

**Comment by xboxone08** [comment]
I agree

**Comment by leha-code** [comment]
You should ask the [RaspberryJuice](https://github.com/zhuowei/RaspberryJuice) developers to add this (this won't be added into Minecraft Pi, but CAN be added with third-party mods such as mcpi-reborn). Once this is implemented in a plugin, one can add the function to the API.
