### ISSUE TITLE
Create an equivalent of the /give command plz?

### ISSUE THREAD

**Issue by xboxone08** [martinohanlon/mcpi#18]

**Comment by TheBrokenRail** [comment]
This isn't possible. This project is an implementation of the MCPI API client, adding a new API function (like `/give`) would require also modifying the API server. And since MCPI was released in 2013 and hasn't been updated since, that is unlikely to happen.

**Comment by martinohanlon** [comment]
What the @TheBrokenRail said :) Thank you

Closing
