### ISSUE TITLE
mcpi on pi

### ISSUE THREAD

**Issue by Eman10826** [martinohanlon/mcpi#20]
I removed mcpi on my raspberry pi, how do I reinstall it?

**Comment by jacobxycat1395** [comment]
If you're talking about the python package, you'll need to use `pip3 install mcpi` or if you're not using python3, `pip install mcpi`. If you're talking about the Minecraft Pi application itself, you need to use `sudo apt install minecraft-pi`.

**Comment by martinohanlon** [comment]
@jacobxycat1395 Thank you. Closing
