### ISSUE TITLE
Unclear documentation on `Minecraft.camera.setFollow(entityId)`

### ISSUE THREAD

**Issue by xboxone08** [martinohanlon/mcpi#29]
The [official API reference](https://www.stuffaboutcode.com/p/minecraft-api-reference.html)'s documentation upon the aforementioned method is ambiguous.

In the description it says:
>"Set camera mode to follow an entity ([entityId])"

While in the code, the comment suggests that `entityId` is that of the entity who's camera is being changed:
```python3
#set camera mode to follow for a specific player
mc.camera.setFollow(entityId)
```
So, does `entityId` refer to that of the player to follow or the player whose camera view is changed?

**Comment by martinohanlon** [comment]
When you say "official" API reference. You mean the reference that I created because no documentation existed...

>So, does entityId refer to that of the player to follow or the player whose camera view is changed?

No idea. Perhaps try it, find out and let us know.

**Comment by xboxone08** [comment]
You see, I only have one Raspberry Pi as of now, so I can't. I want to know for my multiplayer code. Hopefully someone else will test it out. I assumed it was official since it is listed as the reference on the README.md of this repository. Please don't tell me this repository is not official. Then I'd be completely lost.

btw, is there any reason why you aren't merging #24? I thought you might have been offline or something.
@martinohanlon

**Comment by martinohanlon** [comment]
This repository is not 'official'. Mojang only provided limited support for
Minecraft Pi edition, the original mcpi library provided was only Python 2.

I put it onto GitHub and pypi it as no one else did.

**Comment by Bigjango13** [comment]
> You see, I only have one Raspberry Pi as of now, so I can't.

Can't you launch Minecraft Pi more than once and join on LAN?

I tried out `Minecraft.camera.setFollow(entityId)` and `entityId` refers to the entity to follow, it sets the camera of the player that is using the API to hover above the entity that is specified by `entityId`.

**Comment by xboxone08** [comment]
@Bigjango13 that's possible? I didn't know that. That's cool. I've been waiting for so long for another Raspberry Pi and it turns out I can join my own LAN game. Huh. Not sure if my puny Raspberry Pi Zero W can handle it though. Thank you for the clarification on `entityId`.
