### ISSUE TITLE
position issue

### ISSUE THREAD

**Issue by LinsenHou** [martinohanlon/mcpi#3]
I got the player postion through mc.player.getTilePos() ,then I press the F3 to check the postion, I found they are different, Why does this happen ? I suppose they should be the same. Pls help on this. Thanks a lot.
![image](https://user-images.githubusercontent.com/9674322/61351766-32acdf00-a89e-11e9-8b71-2f3b7bfd1827.png)

**Comment by martinohanlon** [comment]
This is by design as locations are relative to the spawn point, this is to emulate the original behaviour of the API created for the Raspberry Pi.

You can change this to use absolute positions in the `config.yml` of the RaspberryJuice plugin. https://github.com/zhuowei/RaspberryJuice#config
