### ISSUE TITLE
How do I take a screenshot?

### ISSUE THREAD

**Issue by hyuk199** [martinohanlon/mcpi#32]
I want to take a screenshot of a building from a specific location, looking in a specific direction.
Is this possible?
And `mc.camera.setPos(x,y,z)` is not working

**Comment by Bigjango13** [comment]
Taking a screenshot isn't possible with `mcpi`, you still need to press F2 to take a screenshot, and unless I'm mistaken, you cannot change the camera angle. What do you mean by `mc.camera.setPos(x,y,z)` is not working, does it move the camera? What version of minecraft/RaspberryJuice are you on?

**Comment by hyuk199** [comment]
> Taking a screenshot isn't possible with `mcpi`, you still need to press F2 to take a screenshot, and unless I'm mistaken, you cannot change the camera angle. What do you mean by `mc.camera.setPos(x,y,z)` is not working, does it move the camera? What version of minecraft/RaspberryJuice are you on?

I am using `minecraft 1.12.2` /`RaspberryJuice 1.11`.
When I type `mc.camera.setPos(x,y,z)`,  it doesn't move the camera and nothing happen.

**Comment by Bigjango13** [comment]
Unfortunately, I don't think RaspberryJuice supports `camera.setPos`. [`handleCommand`](https://github.com/zhuowei/RaspberryJuice/blob/991b1be45f313417ae43d9de7c6a7eb0b2faf2ba/src/main/java/net/zhuoweizhang/raspberryjuice/RemoteSession.java#L166) doesn't have a handler for it, however you might be able to teleport the player and set rotation using `player.setPos` and `player.setDirection`.

**Comment by hyuk199** [comment]
> Unfortunately, I don't think RaspberryJuice supports `camera.setPos`. [`handleCommand`](https://github.com/zhuowei/RaspberryJuice/blob/991b1be45f313417ae43d9de7c6a7eb0b2faf2ba/src/main/java/net/zhuoweizhang/raspberryjuice/RemoteSession.java#L166) doesn't have a handler for it, however you might be able to teleport the player and set rotation using `player.setPos` and `player.setDirection`.

Thank you `player.setDirection` is what I want!
