### ISSUE TITLE
Using setBlocks to set a region to air ignores copper ore  

### ISSUE THREAD

**Issue by EishoTek** [martinohanlon/mcpi#33]
As title 
Python version 3.9.12 
mcpi 1.2.1

**Comment by martinohanlon** [comment]
This is highly unlikely to be an issue with mcpi more likely to be an issue
with RaspberryJuice (or Minecraft:pi edition, or whatever else).

mcpi only passes the instructions.

**Comment by martinohanlon** [comment]
Closing as not a problem with mcpi. Obviously if you think / can prove otherwise happy to reopen.
