### ISSUE TITLE
My friend cant connect to my server

### ISSUE THREAD

**Issue by Waxbyz** [martinohanlon/mcpi#35]
:)

**Comment by martinohanlon** [comment]
:(

**Comment by Waxbyz** [comment]
Will you help me?

**Comment by martinohanlon** [comment]
Its difficult without any information.

Why cant they? Did they receive an error? How are you trying to connect - on the same network, over the internet? What have you done to try and resolve the issue? What's the server - mcpi running on a Pi, or are you using something like Raspberry Juice? What version of Minecraft? etc, etc.

There is no one single reason why "My friend cant connect to my server". If you can provide more information people maybe able to help you. Its useful to give as much information as possible. Its highly unlikely that the reason your friend cant connect to your server will be a problem with mcpi. 

¯\_(ツ)_/¯

**Comment by Waxbyz** [comment]
He doesn't have a server in the list, his computer is connected to the same network as mine. I tried to change the ports to 4711, but without success. Raspberry Juice plugin is installed, minecraft version 1.20.4. I hope this information will be enough. :)

**Comment by martinohanlon** [comment]
Ok, so you're running a java Minecraft server (i.e. spigot) which has the RaspberryJuice plugin installed. 

I am going to assume that your friend is trying to join your Minecraft server to "play the game" i.e. he isn't trying to connect to mcpi using Python and that you are running the server on your computer (i.e. local machine).

There is information here (https://www.minecraft.net/en-us/article/how-play-minecraft-server) on "how to connect to a java edition server".

You will need to find the local IP address of your computer - there is information on how to do this here (https://www.whatismybrowser.com/detect/what-is-my-local-ip-address)

Use the "direct connection" option in the Minecraft Multiplayer menu, enter your local IP, and try to connect. You dont need to change the port to 4711, this is what mcpi and Python use.

If you still cant connect I would suggest looking at whether something might be blocking the connection to your computer (maybe a local firewall or permissions).

I hope this helps.

Closing as not an issue with mcpi. Feel free to re-open if my assumption is wrong and this is an issue with mcpi.
