### ISSUE TITLE
library not working with my local server.

### ISSUE THREAD

**Issue by javierarilos** [martinohanlon/mcpi#38]
Hi there!
we're following instructions for setting up a learning environment for my child to learn to code Python with Minecraft following the book "Learn to Program with Minecraft: Transform Your World with the Power of Python"
https://www.amazon.com/Learn-Program-Minecraft-Transform-Python/dp/1593276702

We're new to Minecraft, but I can understand some Python.

Our setup:
1. Mac Sonoma 14.2.1
2. Python 3.9
3. Minecraft server 1.21
4. mcpi 1.2.1

With this setup, we're able to do a `Minecraft.create` but when doing other operations, it seems like the API and the server can't talk to each other properly.

For example, executing `mc.player.getPos()` throws an Exception, stacktrace below.

Can someone please help us?

All the best.
Javier

```
 mc.player.getPos()
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[3], line 1
----> 1 mc.player.getPos()

File /Library/Python/3.9/site-packages/mcpi/minecraft.py:153, in CmdPlayer.getPos(self)
    152 def getPos(self):
--> 153     return CmdPositioner.getPos(self, [])

File /Library/Python/3.9/site-packages/mcpi/minecraft.py:46, in CmdPositioner.getPos(self, id)
     44 def getPos(self, id):
     45     """Get entity position (entityId:int) => Vec3"""
---> 46     s = self.conn.sendReceive(self.pkg + b".getPos", id)
     47     return Vec3(*list(map(float, s.split(","))))

File /Library/Python/3.9/site-packages/mcpi/connection.py:62, in Connection.sendReceive(self, *data)
     60 """Sends and receive data"""
     61 self.send(*data)
---> 62 return self.receive()

File /Library/Python/3.9/site-packages/mcpi/connection.py:54, in Connection.receive(self)
     52 def receive(self):
     53     """Receives data. Note that the trailing newline '\n' is trimmed"""
---> 54     s = self.socket.makefile("r").readline().rstrip("\n")
     55     if s == Connection.RequestFailed:
     56         raise RequestError("%s failed"%self.lastSent.strip())

File /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py:704, in SocketIO.readinto(self, b)
    702 while True:
    703     try:
--> 704         return self._sock.recv_into(b)
    705     except timeout:
    706         self._timeout_occurred = True

KeyboardInterrupt:

In [4]: mc.player.getPos()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 mc.player.getPos()

File /Library/Python/3.9/site-packages/mcpi/minecraft.py:153, in CmdPlayer.getPos(self)
    152 def getPos(self):
--> 153     return CmdPositioner.getPos(self, [])

File /Library/Python/3.9/site-packages/mcpi/minecraft.py:47, in CmdPositioner.getPos(self, id)
     45 """Get entity position (entityId:int) => Vec3"""
     46 s = self.conn.sendReceive(self.pkg + b".getPos", id)
---> 47 return Vec3(*list(map(float, s.split(","))))

ValueError: could not convert string to float: ''
```

**Comment by javierarilos** [comment]
Also, in ipython, when I do that, I see a lot of these messages:

```
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
Last Message: <b'world.setBlock(10,10,10,1,0)'>
Drained Data: <b''>
```

**Comment by Bigjango13** [comment]
MCJE doesn't know these commands by itself, it needs a mod to translate it into something it understands. The book should go over which mod you need and how to install it, but in case it doesn't, RaspberryJuice is the most commonly used. Unfortunately none of these mods have been updated to 1.21 to my knowledge.

**Comment by javierarilos** [comment]
Thank you very much!
wondering if there are big changes in the newer versions of the server
(1.21)... if not, I might contribute with a PR.
Do you know where I can find information on the different versions of the
protocol?

**Comment by Bigjango13** [comment]
I'm a little confused, the protocol isn't in MCJE, and as far as I know never has been. The protocol was invented in Minecraft Pi Edition[^1]. this library is a python frontend to it[^2]. To use it with MCJE, you need a mod that implements this protocol, if you wanted to use it in modern Java Edition, you would have to make a mod that implenents this protocol.

[^1]: Unofficially documented here: https://www.stuffaboutcode.com/p/minecraft-api-reference.html
[^2]: For different languages, there are different frontends: https://mcpirevival.miraheze.org/wiki/Minecraft:_Pi_Edition_Scripting_API

**Comment by martinohanlon** [comment]
There are no future planned releases of RaspberryJuice - https://github.com/zhuowei/RaspberryJuice - it maybe that someone picks ups the project and makes a v2 but so far that hasnt happened.

Fyi - You can run RaspberryJuice with later versions of Minecraft, but not all features of the later versions will be available through the API - you can get the plugin at - https://www.spigotmc.org/resources/raspberryjuice.22724/

Im going to close the issue as it isnt a problem with mcpi
