### ISSUE TITLE
是否打算适配MC 1.21呢？（Do you plan to adapt to MC 1.21?）

### ISSUE THREAD

**Issue by pyly-pyly** [martinohanlon/mcpi#39]
是否打算适配MC 1.21呢？（Do you plan to adapt to MC 1.21?）
因为mcpi.Block似乎**缺少很多新版MC的方块**
Because mcpi. Block seems to be missing a lot of blocks from the new version of the MC

**Comment by Bigjango13** [comment]
Non-numeric block ids make this harder (for example: https://minecraft.wiki/w/Java_Edition_1.13/Flattening). That may also break compatibility with MCPI.

**Comment by pyly-pyly** [comment]
正在写代码......请稍后再发Writing code......Please send it later---这不是本人回信------This is not a personal reply---

**Comment by pyly-pyly** [comment]
但MC 1.12 已经**很旧了**，现在的主流版本都是1.19 1.20 1.21
是否可以放弃兼容1.12及以下版本并抛弃数字方块ID

---
But MC 1.12 is **very old**, and the current mainstream versions are all 1.19 1.20 1.21
Is it possible to discard compatibility with 1.12 and below and discard the numeric block ID

**Comment by martinohanlon** [comment]
It isn't just changing mcpi, the API would also need to change to support
it.

You can read about why this won't be progressed here -
https://github.com/zhuowei/RaspberryJuice/pull/84#issuecomment-544295161

**Comment by martinohanlon** [comment]
Closing - this is not within the scope of mcpi to implement.
