### ISSUE TITLE
Added MC command support

### ISSUE THREAD

**Issue by pyly-pyly** [martinohanlon/mcpi#40]
Added MC command support.
A function is used to invoke commands:
```python
def command(command: str) -> bool:
    # Communication codes.
```

**Comment by Bigjango13** [comment]
Just use post to chat?

**Comment by pyly-pyly** [comment]
Commands are **other commands**
For example, kill and give
instead of postToChat()

---
```python
def command(command: str) -> bool:
    '''Check whether the bool command is successfully executed'''
    # Other codes
```

**Comment by martinohanlon** [comment]
Just adding this to mcpi wont allow it to be used. The corresponding API would also need to be changed. This is not within the scope of mcpi to implement.
