### ISSUE TITLE
player.setRotation()?

### ISSUE THREAD

**Issue by wr200m** [martinohanlon/mcpi#5]
Thank you for mcpi! Will you at some point implement setRotation()?

**Comment by martinohanlon** [comment]
Do you mean will setRotation be implemented in Minecraft: Pi edition? If so, this is not something I can do, it would require a change to Minecraft: Pi edition which Mojang would have to do.

If you are looking for the mcpi python library for the RaspberryJuice plugin - you can find it here https://github.com/zhuowei/RaspberryJuice/tree/master/src/main/resources/mcpi/api/python/modded/mcpi

**Comment by wr200m** [comment]
Thank you!
