### ISSUE TITLE
Plans to support material strings insted of blocks ids

### ISSUE THREAD

**Issue by acs** [martinohanlon/mcpi#7]
Hi Martin,

First of all, thank your for your great job helping in the support of Python programming in Minecraft.

As you know, with MC 1.13 the changes to using strings instead of ids for the blocks have broken mcpi for actual MC releases. Do you plan to support a mapping between current block names and strings, instead of ids?

IMHO this is the first step in order to support string defined blocks (materials) in Python for Minecraft. I have read your opinion at https://github.com/zhuowei/RaspberryJuice/pull/84#issuecomment-544295161 and probably you don't plan to change this library.

Do you think that a new mcpi2 will be needed to support MC > 1.13?

I have tested the https://github.com/zhuowei/RaspberryJuice/pull/84 and with a minor change in mcpi so it accepts strings in setBlock, it works with:

`mc.setBlock(self.position.x, self.position.y, self.position.z, "bedrock")
`

And thanks for updating mcpi to RaspberryJuice 1.12.2 ... spawning entities is great (among the other calls now supported).

I am working in https://github.com/juntosdesdecasa/mcthings (where I am using mcpi, of course, and also McDrawings) and my goal is to have the best platform for learning Python for kids.

**Comment by lisjump** [comment]
I was going to do some experimenting with the entities today to add some new entity IDs.  When I get a more complete list, is it worth putting in a pull request?

**Comment by martinohanlon** [comment]
> Do you think that a new mcpi2 will be needed to support MC > 1.13?
If there is a RaspberryJuice 2.0 I would advocate an mcpi2

**Comment by lasteamlab** [comment]
@sprouviere already has done this.  With his permission, I'm pulling it into github https://github.com/lasteamlab/mcpi2
along with RaspberryJuice2 (which is awaiting his updates, but forked from @minecraftdawn) https://github.com/lasteamlab/RaspberryJuice2
