### ISSUE TITLE
mc.player.getTilePos() will only get first player position

### ISSUE THREAD

**Issue by stoneskin** [martinohanlon/mcpi#8]
when I play with my kids.   I found the mc.player.getTilePos() looks will only get the first player in the server.
same like setTilePos()
Is it possible to set the player by id?

**Comment by martinohanlon** [comment]
The entity functions allow you to interact with multi players (and other entities).

**Comment by martinohanlon** [comment]
API is here https://www.stuffaboutcode.com/p/minecraft-api-reference.html

**Comment by ghost** [comment]
Why do mcpi.getTilePos() didn't respond?

**Comment by Bigjango13** [comment]
> Why do mcpi.getTilePos() didn't respond?

That's weird, it should be supported on vanilla MCPI, RaspberryJuice, and RaspberryJamMod. Which are you using?
